name: Update Views

on:
  workflow_dispatch:

jobs:
  update-views:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Update Views Count
        run: echo $(curl -s https://api.github.com/repos/your-username/your-repo-name | jq -r '.watchers_count') > views.txt

      - name: Update README
        run: sed -i "s~!\[Visitor's Count\](https://profile-counter.glitch.me/Supprise0901_TVBox_warehouse/count.svg)~![Visitor's Count](views.svg)~" README.md

      - name: Commit and push changes
        run: |
          git add views.txt README.md
          git commit -m "Update views count [skip ci]"
          git push origin HEAD